name = "SeparatingHyperplanes"
uuid = "197ed399-51c8-4969-bb6f-74604dde59b7"
authors = ["Devansh Agrawal <devansh@umich.edu> and contributors"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
OSQP = "0.8.1"
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
